HW03 Ex01-16
userChernov/HomeworkTasks pull request #4
Opened 2024-09-16 07:18 UTC by userChernov

Первая часть домашнего Задания Hw03

2024-09-16 07:25 UTC, userChernov commented
Еще в Ex09 прописан namespace Ex3
И сама задача близка к той, что дается в Ex03

2024-10-07 11:39 UTC, pimushkin requested changes

2024-10-07 11:39 UTC, pimushkin commented on Hw03/Ex11/Program.cs
> +    }
По условию задачи требуется, чтобы поле owner в классах Cat и Dog было типа Human, а не string. В твоём решении поле owner имеет тип string. Необходимо изменить тип поля owner на Human и соответствующим образом изменить присваивания и вывод

2024-11-05 09:40 UTC, pimushkin requested changes

2024-11-05 09:40 UTC, pimushkin commented on Hw04/Ex09/Program.cs
> +            if (a > 30 && a <= 100)
Здесь допущена ошибка в условии. Число 30 не включено в интервал. По условию задачи интервал от 30 до 100 включительно

2024-11-05 09:40 UTC, pimushkin commented on Hw04/Ex14/Program.cs
> +                num = Convert.ToInt32(rand);
Неправильно используешь `Convert.ToInt32(rand);`. `rand` - это объект класса `Random`, а не число

Также не стоит инициализировать `Random` внутри цикла. Ты его можешь инициализировать один раз за пределами цикла и использовать метод `Next(x, y)` у созданного объекта внутри цикла (либо сделать вообще без цикла)

2024-11-05 09:40 UTC, pimushkin commented on Hw04/Ex15/Program.cs
> +                Random rand = new Random();
Как и в 14-ой задаче, рекомендую вынести инициализацию `Random` за пределы цикла

2024-11-05 09:40 UTC, pimushkin commented on Hw04/E18/Program.cs
> +            int[] numbers = [a, b, c, d];
Не совсем корректно иницилизируешь массив. Правильно так:

```csharp
int[] numbers = new int[] { a, b, c, d };
```

2024-11-05 09:40 UTC, pimushkin commented on Hw04/E18/Program.cs
> +                Random rand = new Random();
Тут тоже инициализацию `Random` следует вынести за пределы цикла

2024-11-05 09:40 UTC, pimushkin commented on Hw04/Ex26/Program.cs
> +            //for (int i = 0; i <= 100; i+2) - А ТАК МОЖНО ДЕЛАТЬ?
Не совсем так. Правильнее будет следующим образом:

```csharp
for (int i = 2; i <= 100; i += 2)
{
    Console.Write($"{i} ");
}
```

2024-11-05 09:40 UTC, pimushkin commented on Hw04/Ex11/Program.cs
> +        public static void CheckYear(float year)
Годы выражаются целыми числами, так что следует использовать тип `int` вместо `float`. Если ты используешь `float`, то это может привести к неточностям при вычислениях с остатком (%), так как операции с плавающей запятой могут не давать ожидаемых результатов при использовании с оператором остатка

2024-11-05 09:40 UTC, pimushkin commented on Hw04/Ex11/Program.cs
> +            if ((year % 4 == 0) && (year % 400 == 0 || (year % 100 > 0 || year % 100 < 0)))
Логика условия получилась сложная и неочевидная. Давай разберем и упростим твоё условие:

Начнём с `(year % 100 > 0 || year % 100 < 0)`:
Это выражение всегда будет истинным, кроме случая, когда `year % 100 == 0`. Почему? Причина в том, что если остаток от деления на 100 не равен 0, то он либо больше 0, либо меньше 0. Можно упростить до `year % 100 != 0`.

Окей. Получается следующим образом:
```csharp
if ((year % 4 == 0) && (year % 400 == 0 || year % 100 != 0))
```

Какие у нас есть условия сейчас:
- `year % 4 == 0`, который проверяет, делится ли год на 4 без остатка
- `year % 400 == 0`, который проверяет, делится ли год на 400 без остатка
- и `year % 100 != 0`, который проверяет, что год не делится на 100 без остатка

Значит итоговая логика нашего условия теперь следующая:
Год является високосным, если он делится на 4 и (делится на 400 или не делится на 100)
Что соответствует правилам определения високосного года

Но корректным и более читаемым я бы сказал следующий вариант реализации:

```csharp
public static void CheckYear(int year)
{
    if (year % 4 != 0)
    {
        Console.WriteLine($"Год {year} является НЕ високосным");
    }
    else if (year % 100 != 0)
    {
        Console.WriteLine($"Год {year} является високосным");
    }
    else if (year % 400 != 0)
    {
        Console.WriteLine($"Год {year} является НЕ високосным");
    }
    else
    {
        Console.WriteLine($"Год {year} является високосным");
    }
}
```

Тут логика разделена на четкие и понятные условия, которые последовательно проверяют каждое правило определения високосного года + используется `int`, а не `float`, о чём я упомянул в другом комментарии

2024-11-06 10:24 UTC, userChernov commented on Hw03/Ex11/Program.cs
> +    }
Исправил

2024-12-01 09:54 UTC, pimushkin submitted a review, later dismissed

2024-12-01 17:33 UTC, userChernov commented on Hw04/Ex09/Program.cs
> +            if (a > 30 && a <= 100)
исправил

2024-12-01 17:34 UTC, userChernov commented on Hw04/Ex14/Program.cs
> +                num = Convert.ToInt32(rand);
понял, исправил

2024-12-01 17:35 UTC, userChernov commented on Hw04/Ex15/Program.cs
> +                Random rand = new Random();
исправил

2024-12-01 17:45 UTC, userChernov commented on Hw04/E18/Program.cs
> +            int[] numbers = [a, b, c, d];
исправил

2024-12-01 17:45 UTC, userChernov commented on Hw04/E18/Program.cs
> +                Random rand = new Random();
вынес инициализацию за цикл

2024-12-01 17:48 UTC, userChernov commented on Hw04/Ex26/Program.cs
> +            //for (int i = 0; i <= 100; i+2) - А ТАК МОЖНО ДЕЛАТЬ?
исправил

2024-12-01 22:46 UTC, userChernov commented on Hw04/Ex11/Program.cs
> +            if ((year % 4 == 0) && (year % 400 == 0 || (year % 100 > 0 || year % 100 < 0)))
исправил

2024-12-02 15:05 UTC, pimushkin approved these changes

2024-12-02 15:07 UTC, merged