Hw05
userChernov/HomeworkTasks pull request #6
Opened 2024-11-05 08:27 UTC by userChernov

2024-11-06 15:09 UTC, pimushkin requested changes

2024-11-06 15:09 UTC, pimushkin commented on Hw05/Ex09/Program.cs
> +        public int count = 0;
Тут допущена ошибка. Переменная `count` должна быть **статической**, так как она подсчитывает общее количество экземпляров класса. В твоём текущем решении `count` является экземпляром класса и обнуляется при каждом создании нового объекта

2024-11-06 15:09 UTC, pimushkin commented on Hw05/Ex14/Program.cs
> +        public string pet;
Получилось неполное решение. В классе `Human` поле `pet` должно быть типа `Cat`, и в конструкторе `Human` нужно принимать экземпляр класса `Cat` и присваивать его полю `pet`. В текущем решении поле `pet` имеет тип `string`, что не соответствует требованиям задачи

По шагам как исправить:

1. Изменяем тип поля `pet` в классе `Human` на `Cat`:

```csharp
public class Human
{
    public string name;
    public string address;
    public Cat pet; // Изменено с string на Cat

    // ...
}
```

2. В конструкторе класса `Human` принимаем экземпляр класса `Cat` и присваиваем его полю `pet`:

```csharp
public Human(Cat pet)
{
    this.name = "Anton";
    this.address = "Произвольный адрес";
    this.pet = pet;
}
```

3. В конструкторе класса `Cat` передаем текущий экземпляр (`this`) в конструктор `Human`:

```csharp
public Cat(string name)
{
    this.name = name;
    this.owner = new Human(this);
}
```

4. Переопределяем метод `ToString()` в классе `Cat`, используя поля класса `Human`:

```csharp
public override string ToString()
{
    return $"Меня зовут: {name}, а моего хозяина зовут: {owner.name}. Мы с ним вместе живем по адресу: {owner.address}!";
}
```

Как это всё работает по итогу:

- Мы сделали поле `pet` типа `Cat`, чтобы хранить ссылку на экземпляр питомца
- Конструктор `Human` принимает `Cat` в качестве параметра и устанавливать его в поле `pet`
- При создании нового `Cat`, мы создаём нового `Human`, передавая ему текущий экземпляр `Cat`
- Таким образом, устанавливается двусторонняя связь между владельцем и питомцем

Что касается примера использования, то выглядеть это может следующим образом:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine(new Cat("Барсик"));
    }
}
```

2024-11-06 15:09 UTC, pimushkin commented on Hw05/Ex25/Program.cs
> +        }
Метод `CatNullifier` должен принимать экземпляр класса Cat в качестве параметра и делать его недостижимым. Сейчас в решении метод не принимает параметров и возвращает null. И напоминаю, что в C# изменить ссылку на объект вне метода без использования ref или out параметров невозможно

2024-11-06 15:09 UTC, pimushkin commented on Hw05/Ex26/Program.cs
Отсутствует деструктор класса `Program`, в котором должно увеличиваться значение `deleteCount` при уничтожении экземпляра класса. В текущем решении счетчик увеличивается в методе `Main()`, что не соответствует требованиям задачи

2024-11-06 15:09 UTC, pimushkin commented on Hw05/Ex27/Program.cs
Нет решения 😢

2024-11-06 16:42 UTC, userChernov commented on Hw05/Ex09/Program.cs
> +        public int count = 0;
Исправил

2024-11-06 16:48 UTC, userChernov commented on Hw05/Ex14/Program.cs
> +        public string pet;
Исправил

2024-11-12 19:43 UTC, userChernov commented on Hw05/Ex25/Program.cs
> +        }
Исправил

2024-11-12 19:43 UTC, userChernov commented on Hw05/Ex26/Program.cs
Исправил

2024-11-12 19:43 UTC, userChernov commented on Hw05/Ex27/Program.cs
Исправил

2024-12-01 09:45 UTC, pimushkin submitted a review, later dismissed

2024-12-01 09:45 UTC, pimushkin commented on Hw05/E35/E35.csproj
Не нужный проект. Можно удалить

2024-12-01 09:45 UTC, pimushkin commented on Hw05/Ex33/Program.cs
> +    enum CarModels
По условию задачи, перечисление `CarModels` должно быть публичным

2024-12-01 16:05 UTC, userChernov commented on Hw05/Ex33/Program.cs
> +    enum CarModels
исправил

2024-12-02 15:12 UTC, userChernov commented on Hw05/E35/E35.csproj
я не понимаю, у меня в вскоде нет Е35, а тут он есть! как его удалить?

2024-12-02 15:13 UTC, userChernov commented on Hw05/E35/E35.csproj
1111

2024-12-02 15:24 UTC, pimushkin approved these changes

2024-12-02 15:24 UTC, merged