Hw06
userChernov/HomeworkTasks pull request #7
Opened 2024-11-22 13:29 UTC by userChernov

2024-12-22 23:32 UTC, pimushkin requested changes

2024-12-22 23:32 UTC, pimushkin commented on Hw06/Ex09/Program.cs
> +    }
По условию задачи нужно было объявить в структуре `CustomLine` **не** статические поля `length` и `symbol`. Метод `PrintLine()` нужно было объявить как статический , который принимает в качестве параметра экземпляр `CustomLine` и выводит информацию на экран. В качестве проверки соотвествия этому условию, можешь воспользоваться кодом ниже:
```csharp
public static void Main(string[] args)
{
    CustomLine line1 = new CustomLine(10, '*');
    CustomLine line2 = new CustomLine(10, '8');
    CustomLine line3 = new CustomLine(10, '$');

    CustomLine.PrintLine(line1);
    CustomLine.PrintLine(line2);
    CustomLine.PrintLine(line3);
}
```

2024-12-22 23:32 UTC, pimushkin commented on Hw06/Ex13/Program.cs
> +            return Math.Sqrt( Math.Pow((x2-x1), 2) - Math.Pow((y2-y1), 2) );
Формула имеют небольшую ошибку в знаке. Вместо `Math.Sqrt(Math.Pow(...) - Math.Pow(...))` должно быть `Math.Sqrt(Math.Pow(...) + Math.Pow(...))`

2024-12-22 23:32 UTC, pimushkin commented on Hw06/Ex19/Program.cs
> +            bool needSort = true;
У тебя переменная `needSort` объявлена **до** цикла и нигде не сбрасывается обратно в `true` для каждого следующего слова. Как только встретится слово с цифрой, `needSort` станет `false`, и дальше все слова перестанут сортироваться. Чтобы решить проблему, можешь перед внутренним циклом для каждого слова обнуляйте или заново инициализируйте `needSort = true;`

2025-01-06 19:13 UTC, userChernov commented on Hw06/Ex09/Program.cs
> +    }
Исправил

2025-01-06 19:18 UTC, userChernov commented on Hw06/Ex13/Program.cs
> +            return Math.Sqrt( Math.Pow((x2-x1), 2) - Math.Pow((y2-y1), 2) );
Исправил

2025-01-13 09:25 UTC, pimushkin approved these changes

2025-01-13 09:25 UTC, merged