Hw07
userChernov/HomeworkTasks pull request #8
Opened 2024-12-17 09:06 UTC by userChernov

2025-01-14 19:58 UTC, pimushkin requested changes

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex04/Program.cs
Твой код полностью удаляет все элементы, у которых есть дубликаты, т.е. если элемент встретился более одного раза, то и "первый", и "второй" экземпляры в итоге удаляются целиком. Тут же требовалось "избавиться от повторов" так, чтобы остался один экземпляр каждого уникального элемента

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex05/Program.cs
> +    public class Cat()
Тут лишние скобки

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex05/Program.cs
> +                Cat.allCats.Add(cat);
По условию задачи при создании каждого экземпляра класса `Cat` он должен сам добавляться в `allCats`.
Ты же это делаешь вручную из `Main()`, что тоже как бы рабочий вариант, но не соответствует формулировке "реализовать класс таким образом, чтобы при создании кота он автоматически попадал в `allCats`"

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex08/Program.cs
> +                    list.RemoveAt(i);
Удаление элементов внутри `for`, где `i` идёт по возрастанию, часто приводит к тому, что мы пропускаем какой-нибудь элемент после `RemoveAt(i)`. То есть сразу после удаления код `list.RemoveAt(i)` сдвигает элементы влево, а также выполняется `i++`, и в итоге это приводит к тому, что следующая строка может быть пропущена или может случиться `IndexOutOfRangeException`

В данном конкретно случае проблема в том, что после `RemoveAt(i)` ты не уменьшаешь `i` и сразу идешь дальше по циклу, а массив стал короче на один. При большом числе строк почти неизбежна ошибка или пропуски

В целом, логика замены верная, но способ удаления внутри одного и того же цикла не надежен. Желательно переписать. Я тебе рекомендую сделать три отдельных прохода (или копию списка, или идти с конца к началу, или использовать LINQ для фильтрации), чтобы избежать путаницы

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex16/Program.cs
> +                    localset.Remove(item);
У тебя код считает среднее, потом удаляет элементы из того же множества `localset` в цикле `foreach`. Это может привести к ошибке при работе с `HashSet`, поскольку удалять из перебираемой коллекции небезопасно

По сути задача решена, но в реальной работе такой код может вызывать исключение при множествах больших размеров. Нужно либо сначала собрать в отдельный список все элементы под удаление, а после цикла убрать их из `set`, либо идти другим способом

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex18/Program.cs
> +            for (int i = 0; i < names.Count - 1; i++)
Тут классический недочёт (последнее имя не всегда выводится). При вводе 10 разных имён, 9 из них попадут в цикл, а 10-й не попадет в вывод. Следовательно будет неточность. Стоит доработать, чтобы учесть последний элемент

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex19/Program.cs
> +                Console.WriteLine(item);
Основная реализация правильная. Формально нужно вывести только вторую коллекцию (уникальные) и лучше выводить `item.Value`, а не весь `KeyValuePair`

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex22/Program.cs
> +            return (dateB - dateA).Milliseconds;
Код возвращает неправильное значение. `TimeSpan.Milliseconds` даёт только _доли от целых секунд_ (т.е. остаток 0..999), а не общее количество миллисекунд во всей разнице. Для полного количества миллисекунд нужно `TimeSpan.TotalMilliseconds`, а затем привести к `long`

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex23/Program.cs
> +            Console.WriteLine((date.AddDays(33)).DayOfWeek);
Стоит принудительно указать культуру. Иначе может быть русское "Среда" на операционной системе, использующей русский язык

2025-01-14 19:58 UTC, pimushkin commented on Hw07/Ex25/Program.cs
Логика поиска спамеров корректна, но формат вывода не совпадает с условием. Нужно отформатировать строку в соответствии со строкой "ACCOUNT_SURNAME_NAME - IP". Также желательно учесть, что при повторном добавлении одного и того же юзера в словарь `blockedUsers` может вылететь ошибка (если ключ уже есть)

2025-01-16 15:44 UTC, userChernov commented on Hw07/Ex04/Program.cs
Исправил

2025-01-16 15:45 UTC, userChernov commented on Hw07/Ex05/Program.cs
> +    public class Cat()
Исправил

2025-01-16 15:54 UTC, userChernov commented on Hw07/Ex05/Program.cs
> +                Cat.allCats.Add(cat);
Исправил. Плюс я не понял, зачем я вывод на печать в первый раз сделал через енумератор и while. Кажется через for или foreach не сложнее вариант. Оставил оба варианта.

2025-01-21 13:02 UTC, userChernov commented on Hw07/Ex08/Program.cs
> +                    list.RemoveAt(i);
Исправил

2025-01-21 13:09 UTC, userChernov commented on Hw07/Ex16/Program.cs
> +                    localset.Remove(item);
Исправил

2025-01-21 13:18 UTC, userChernov commented on Hw07/Ex18/Program.cs
> +            for (int i = 0; i < names.Count - 1; i++)
исравил

2025-01-21 13:22 UTC, userChernov commented on Hw07/Ex19/Program.cs
> +                Console.WriteLine(item);
Исправил

2025-01-21 13:29 UTC, userChernov commented on Hw07/Ex22/Program.cs
> +            return (dateB - dateA).Milliseconds;
Исправил

2025-01-23 08:13 UTC, userChernov commented on Hw07/Ex23/Program.cs
> +            Console.WriteLine((date.AddDays(33)).DayOfWeek);
Не исправил

2025-02-04 08:52 UTC, pimushkin submitted a review, later dismissed

2025-02-12 09:40 UTC, pimushkin approved these changes

2025-02-12 09:40 UTC, merged