Hw08
userChernov/HomeworkTasks pull request #9
Opened 2024-12-27 08:32 UTC by userChernov

2025-01-16 11:16 UTC, pimushkin requested changes

2025-01-16 11:16 UTC, pimushkin commented on Hw08/Ex01/Program.cs
> +                if ( i % 2 == 0 )
Убедиcь, что «каждый второй» идёт именно там, где нужно

2025-01-16 11:16 UTC, pimushkin commented on Hw08/Ex11/Program.cs
> +                    PrivateDogBank.clients.Remove(item);
Нельзя удалять элементы из `HashSet` (или любой коллекции) прямо в процессе `foreach`. Это выбрасывает исключение или может приводить к пропускам. Как минимум нужно использовать либо `ToList()` внутри цикла, либо `RemoveWhere(...)`, либо отфильтровать и заново пересоздать коллекцию

2025-01-16 11:16 UTC, pimushkin commented on Hw08/Ex12/Program.cs
> +            }
Сортировка должна быть по убыванию, а у вас фактически по возрастанию (неправильные знаки сравнения)

2025-01-16 11:16 UTC, pimushkin commented on Hw08/Ex25/Program.cs
> +                if (item.Account > maxValue)
Задача требует «самое большое по модулю», текущий код не учитывает отрицательные значения

2025-01-16 11:16 UTC, pimushkin commented on Hw08/Ex23/Program.cs
> +        }
Внутри `ElementCount` ты делаешь `for (int i = thisIndex+1; i < arr.Length; i++)` и т.п. Но подсчёт немного странный: фактически ты считаешь, сколько раз ещё встречается элемент после `thisIndex`. Возможно, элемент «a» мог встречаться и раньше. А ещё `firstIndex` присваивается только внутри `if (firstIndex == 0) firstIndex = thisIndex;`, т. е. если у нас символ «a» находится в позиции 0 и в позиции 3, ты вернешь `3 - 0 = 3` в count = 1, а firstIndex = 0.  

Логика выглядит довольно путаной, и **скорее всего** нельзя гарантировать «минимальный индекс первого вхождения» корректно при наличии нескольких «лидеров». Для такой задачи лучше сделать 2 прохода: 
1) Посчитать количество появлений для каждого элемента (в словаре)
2) Определить лучший элемент. При равенстве - тот, у которого индекс первого вхождения минимален

2025-01-23 08:18 UTC, userChernov commented on Hw08/Ex01/Program.cs
> +                if ( i % 2 == 0 )
Исправил

2025-01-23 18:54 UTC, userChernov commented on Hw08/Ex12/Program.cs
> +            }
Исправил

2025-01-23 18:55 UTC, userChernov commented on Hw08/Ex11/Program.cs
> +                    PrivateDogBank.clients.Remove(item);
Исправил

2025-02-07 07:57 UTC, userChernov commented on Hw08/Ex25/Program.cs
> +                if (item.Account > maxValue)
Исправил

2025-02-12 09:42 UTC, pimushkin approved these changes

2025-02-12 09:42 UTC, merged